version: "3.9"
services:
  api:
    image: swat88/skypro_vrusin_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./docker_config.py:/code/default_config.py
  migrations:
    image: swat88/skypro_vrusin_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ./docker_config.py:/code/default_config.py
    command: flask db upgrade
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data
